modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Inventory%20Totem"
logoFile="icon.png"

[[mods]]
modId="inventorytotem"
version="3.0"
displayName="Inventory Totem"
displayURL="https://curseforge.com/minecraft/mc-mods/inventory-totem"
authors="Rick South"
description='''Makes the totem of undying effect work when existing in the player's inventory.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  
Adam E, Alister, aternosorg, Cherriesaurus, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Robert Gilbert, Shana Gitnick, Sija, Tyler Behl, Wendi S   
If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.inventorytotem]]
    modId="collective"
    mandatory=true
    versionRange="[6.17,)"
    ordering="NONE"
    side="BOTH"